version: "3.9"

services:
  eurekaServer:
    image: jyhedhr/eureka_image:latest
    ports:
      - "8030:8761"

  docker-mysql_1:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakpassword
    ports:
      - 3306:3306

  reclamation:
    image: jyhedhr/projet_microservice_image:latest
    ports:
      - "8087:8087"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer
      - docker-mysql_1

  event:
    image: jyhedhr/event:latest
    ports:
      - "8088:8088"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer
      - docker-mysql_1

  Gestionproduit:
    image: jyhedhr/gestion_projet_image:latest
    ports:
      - "8089:8089"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer

  commandeService:
    image: jyhedhr/commande-service:latest
    ports:
      - "8066:8066"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=commande
    depends_on:
      - eurekaServer
      - mongodb

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  gatewayService:
    image: jyhedhr/gateway_image:latest
    ports:
      - "7000:7000"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer
      - Gestionproduit
      - keycloak
      - event
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: art_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  delivery-ms:
    build: ./Delivery-ms
    container_name: delivery-ms
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/art_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
      - eurekaServer

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://docker-mysql_1:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
    command: [ "start-dev" ]
    depends_on:
      - docker-mysql_1

  appuser:
    image: jyhedhr/trelix_back_image:latest  # Replace with actual tag if different
    container_name: back
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: "mongodb+srv://eyanehdi:Trelix123@trelix.1akuy.mongodb.net/Trelix?retryWrites=true&w=majority"


volumes:
  mysql_data:
  keycloak_data:
  mongodb_data:
  postgres-data:
