services:
  #Configuration de eureka container
  eurekaServer:
    build:
      context: ./EurekaServer
    ports:
      - "8030:8761"
    image: "eureka_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
      interval: 30s
      retries: 3
    #Configuration de candidat container
  commandeService:
    build:
      context: ./Commande
    ports:
      - "8066:8066"
    image: "commande-service"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=commande
    depends_on:
      - eurekaServer
      - mongodb
    networks:
      - microservices-network
  
  #configuration de frontend container
  frontend:
    build:
      context: ./front
    ports:
      - "5173:5173"
    image: "front_image"
    environment:
      - VITE_API_URL=http://localhost:7000  # For Vite
    stdin_open: true
    tty: true
    depends_on:
      - gatewayService
    networks:
      - microservices-network
  

  #Configuration de Gateway container
  gatewayService:
    build:
      context: ./Gateway
    ports:
      - "7000:7000"
    image: "gateway_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer
      - commandeService
    networks:
      - microservices-network

  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network
volumes:
  mongodb_data:
  mysql_data:
networks:
  microservices-network:
    driver: bridge

