version: "3.9"  # Compatible version

services:
  # Eureka Server
  eurekaServer:
    build:
      context: ./eureka
    ports:
      - "8030:8761"
    image: "eureka_image"

  # MySQL Database
  #configuration de mysql container
  docker-mysql_1:
    image: "mysql:5.6"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloakpassword
    ports:
      - 3306:3306

  # Gestion Projet Service
  Gestionproduit:
    build:
      context: ./gestionProjet
    ports:
      - "8089:8089"
    image: "gestion_projet_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer

  # API Gateway Service
  gatewayService:
    build:
      context: ./Gateway
    ports:
      - "7000:7000"
    image: "gateway_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer
      - Gestionproduit
      - keycloak

  # Keycloak Authentication Service
  keycloak:
   image: quay.io/keycloak/keycloak:23.0
   container_name: keycloak
   ports:
    - "8080:8080"
   environment:
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin
    KC_DB: mysql
    KC_DB_URL: jdbc:mysql://docker-mysql_1:3306/keycloak
    KC_DB_USERNAME: keycloak
    KC_DB_PASSWORD: keycloakpassword
   command: ["start-dev"]  # Remove --import-realm
   depends_on:
    - docker-mysql_1
    

volumes:
  mysql_data:
  keycloak_data:
