services:
  #Configuration de eureka container
  eurekaServer:
    build:
      context: ./EurekaServer
    ports:
      - "8030:8761"
    image: "eureka_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    #Configuration de candidat container
  commandeService:
    build:
      context: ./Commande
    ports:
      - "8066:8066"
    image: "commande-service"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
      - spring.data.mongodb.host=mongodb
      - spring.data.mongodb.port=27017
      - spring.data.mongodb.database=commande
    depends_on:
      - eurekaServer
      - mongodb
  #configuration de mysql container
  docker-mysql_1:
    image: "mysql:5.6"
    environment:
    - MYSQL_ROOT_PASSWORD=keycloakpassword
    - MYSQL_DATABASE=keycloak
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=keycloakpassword
    ports:
    - "3306:3306"
    volumes:
    - mysql_data:/var/lib/mysql
  #Configuration de Gateway container
  gatewayService:
    build:
      context: ./Gateway
    ports:
      - "7000:7000"
    image: "gateway_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer
      - commandeService
  keycloak:
   image: quay.io/keycloak/keycloak:23.0
   container_name: keycloak
   ports:
    - "8080:8080"
   environment:
    KEYCLOAK_ADMIN: admin
    KEYCLOAK_ADMIN_PASSWORD: admin
    KC_DB: mysql
    KC_DB_URL: jdbc:mysql://docker-mysql_1:3306/keycloak
    KC_DB_USERNAME: keycloak
    KC_DB_PASSWORD: keycloakpassword
   command: ["start-dev"]  # Remove --import-realm
   depends_on:
    - docker-mysql_1
  mongodb:
    image: "mongo"
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
  mysql_data: