version: "24.0.2"
services:
  #Configuration de eureka container
  eurekaServer:
    build:
      context: ./EurekaServer
    ports:
      - "8030:8761"
    image: "eureka_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/

  #Configuration de candidat container
  commandeService:
    build:
      context: ./Commande
    ports:
      - "8066:8066"
    image: "commande_image"
    environment:
        - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer
  #configuration de mysql container
  docker-mysql_1:
    image: "mysql:5.6"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=jobs
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
  #Configuration de Gateway container
  gatewayService:
    build:
      context: ./Gateway
    ports:
      - "7000:7000"
    image: "gateway_image"
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
    depends_on:
      - eurekaServer
      - commandeService