spring.application.name=delivery-ms
server.port=8082

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/art_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Eureka Discovery Configuration
eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka
eureka.client.register-with-eureka=true

spring.cloud.config.enabled=false

# RabbitMQ Configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest