# Application Configuration
spring.application.name=gestionproduit
server.port=8089

# H2 Database Configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2
spring.h2.console.settings.web-allow-others=true

# Datasource
spring.datasource.username=jyhed
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./Database/Data/GestionProduit
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create

# Eureka Configuration
eureka.client.service-url.defaultZone=http://eurekaServer:8761/eureka/
eureka.client.register-with-eureka=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jihedhorchani@gmail.com
spring.mail.password=jfes uekb sgba iegh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=AC9e5369e8195cc957929008da34ecd7f2
twilio.auth.token=b8a360f889c72291621a769b5ce86ab9
twilio.phone.number=+19035467653



spring.cloud.config.enabled=true
spring.cloud.config.uri=http://localhost:8888
spring.config.import=optional:configserver:http://localhost:8888/
welcome.message=Hello from Gestion Produit Service